MyToDoList/Models/ToDos.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;


namespace ToDoApp.Models
{
    public class ToDos
    {
        [Key]
        [Required]
        public string Title { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ToDoID { get; set; }
        public bool IsDone { get; set; }
        public DateTime? CompletedDate { get; set; }
        public DateTime? DueDate { get; set; }

    }
}

MyToDoList/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace ToDoApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

MyToDoList/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using ToDoApp.Data;

namespace ToDoApp.Pages
{
    public class IndexModel : PageModel
    {
        
        [FromForm]
        public Models.ToDos addTask { get; set; }

        private EFContext db = new EFContext();
        
        
        public List<Models.ToDos> ToDos { get; set; }
        

        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            
            _logger = logger;
        }

        // default method to get all todo items from database
        public void OnGet()
        {
            ToDos = db.ToDos.ToList();
        }
        // default OnPost method to create new record
        public void OnPost()
        {
            if (!ModelState.IsValid)
            {
                return ;
            }
            else
            {
                //try to catch if primary key exist 
                try
                {
                    db.ToDos.Add(addTask);
                    db.SaveChanges();
                    ToDos = db.ToDos.ToList();
                }
                catch(Exception e) { Console.WriteLine(e.Message); }
                
            }
            
        }

        //custom OnPost to delete item
        public ActionResult OnPostDelete(string? title)
        {
            if (title != null)
            {
                
                var data = (from todo in db.ToDos
                            where todo.Title == title
                            select todo).SingleOrDefault();

                db.Remove(data);
                db.SaveChanges();
            }
            return RedirectToPage("index");
        }
        //custom OnPost method to update item
        public ActionResult OnPostUpdate(string? title)
        {
            
            if (title != null)
            { 
                var data = (from todo in db.ToDos
                            where todo.Title == title
                            select todo).SingleOrDefault();
                if (data == null)
                {
                    return NotFound();
                }
                if(data.IsDone != addTask.IsDone)
                {
                    addTask.CompletedDate = DateTime.Now;
                }

                //try to catch if primary key exist 
                try
                {
                    db.Remove(data);
                    db.Add(addTask);
                    db.SaveChanges();
                }
                catch (Exception e) { Console.WriteLine(e.Message); }

            }
            return RedirectToPage("index");
        }

        // run onclick cancel
        public void OnPostCancel()
        {
            return ;
        }
    }
}

MyToDoList/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace ToDoApp.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

MyToDoList/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

@section Scripts {
    <script>
        // toggel show hide add new todo div on 'Add Task' button click
    function Showhide() {
        $("#newFrom").toggle();
        }

        // show edit todo item div on click of title in a row on home page view
        function EditTask(e) {
            console.log(e);
            $('#' + e + '').show();
        }

        //close all the edit or new form div on the page
        function CloseForm() {
            $('form').hide();
        }

    </script>
}

    <div class="app">
        <header class="app-header">
            <div class="app-header-logo">
                
                <div class="logo">
                    <h1 class="logo-title">
                        <span>ToDo App</span>
                    </h1>
                </div>
            </div>
        </header>

        <div>
            <div class="app-body-main-content">
                <div style="display: inline-flex;padding: 1%;">
                    <button class="save-button" onclick="Showhide()">Add Task</button>
                </div>
                <div class="card" id="newFrom" style="display:none">
                    <section>
                        <partial name="_newToDo" model="@Model.addTask" />
                    </section>
                    

                </div>

                <div class="app-header-navigation">
                    <div class="tabs">
                        <span class="text-light">
                            Title
                        </span>
                        <span class="text-light">
                            Due Date
                        </span>
                        <span class="text-light">
                            Completed On
                        </span>
                        <span class="text-light">
                            Is Done
                        </span>
                    </div>
                </div>
                <section class="todo-section">
                    @if (!(Model.ToDos == null))
                    {
                        @foreach (Models.ToDos toDo in Model.ToDos)
                        {
                            <div>
                                <partial name="_ToDoList" model="toDo" />
                            </div>

                            <div style="display:none" id="@toDo.ToDoID">
                                <partial name="_editToDo" model="toDo" />
                            </div>

                        }
                    }
            else
            {
                <h1>No record in DataBase !</h1>
            }
                </section>

            </div>

        </div>
    </div>

MyToDoList/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<partial name="_header.cshtml"/>
<body>

    <div class="container">
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow">
                <div class="container">
                    <a class="navbar-brand text-light" asp-area="" asp-page="/Index">ToDoApp</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-page="/ToDo">Completed Tasks</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2021 - ToDoApp - <a asp-area="" asp-page="/Privacy">Privacy</a>
            </div>
        </footer>

        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>

        @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MyToDoList/Pages/Shared/_ToDoList.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{ }
@model ToDoApp.Models.ToDos


            



<section>
    <div class="todos">
        <div class="row">

            <div class="col-sm">
                <span class="span-title" onclick="EditTask(@Model.ToDoID)">@Model.Title</span>

            </div>

            <div class="col-sm">
                <dt>@Model.DueDate</dt>

            </div>
            <div class="col-sm">

                <dt>@Model.CompletedDate</dt>

            </div>

            <div class="col-sm">
                @if (Model.IsDone)
                {
<img src="~/green-tick.png" style="float:right; height:30px; width:30px" /> }
else
{
<img src="~/red-x.png"  style="float:right; height:30px; width:30px"/>}

            </div>
        </div>
    </div>
</section>

               

MyToDoList/Pages/Shared/_editToDo.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model ToDoApp.Models.ToDos

@{
    ViewData["Title"] = "Edit";
}

<form asp-action="Edit" method="post" class="card">
    <div class="row" style="margin:0px">
        <div class="col-sm" style="display:inline-grid;padding:10px">
            <label asp-for="@Model.Title"></label>
            <input style="min-height:30px; min-width:300px;border-radius:5px;font-size:1rem" asp-for="@Model.Title" />

        </div>
        <div class="col-sm" style="display: inline-grid; padding: 10px">
            <label asp-for="@Model.DueDate"></label>
            <input value="" style="min-height: 30px; min-width: 300px; border-radius: 5px; font-size: 1rem" type="date" asp-for="@Model.DueDate" />

        </div>
    </div>

    <div style="display:inline-flex">
        
        <input style="background-color: black;margin-left:9px; font-size: .9rem" type="submit" value="Delete" asp-page-handler="Delete" asp-route-id="@Model.Title" onclick="CloseForm();" class="save-button">
        <input style="background-color: black;margin-left:9px; font-size: .9rem" type="submit" value="Cancel" asp-page-handler="Cancel" onclick="CloseForm();" class="save-button">
        <input style="background-color: black;margin-left:9px; font-size: .9rem" type="submit" asp-page-handler="Update" asp-route-id="@Model.Title" value="Update" onclick="CloseForm();" class="save-button" />
        <div style="margin-left:12px">
            @if (@Model.IsDone)
            {
                <input asp-for="@Model.IsDone" id="i" type="checkbox" checked="checked" />
            }
            else
            {
                <input asp-for="@Model.IsDone" id="i" type="checkbox" />
            }

            <label for="i">Mark Complete</label>
        </div>
    </div>
</form>

MyToDoList/Pages/Shared/_header.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - ToDoApp</title>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </head>




}

MyToDoList/Pages/Shared/_newToDo.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{ }

@model ToDoApp.Models.ToDos


<form method="post">
    <div class="row" style="margin:0px">
        <div class="col-sm" style="display:inline-grid;padding:10px">
            <label asp-for="@Model.Title"></label>
            <input style="min-height:30px; min-width:300px;border-radius:5px;font-size:1rem" asp-for="@Model.Title" />

        </div>
        <div class="col-sm" style="display: inline-grid; padding: 10px">
            <label asp-for="@Model.DueDate"></label>
            <input style="min-height: 30px; min-width: 300px; border-radius: 5px; font-size: 1rem" type="date" asp-for="@Model.DueDate" />

        </div>
    </div>

    <div style="display:block">
        <input style="background-color: black;margin-left:9px; float:right; font-size: .9rem" value="Cancel" asp-page-handler="Cancel" onclick="CloseForm();" type="submit" class="save-button">
        <input style="position: relative; left: 77%; background-color: black; font-size: .9rem" type="submit" value="Add" class="save-button" />

    </div>
</form>

               